### ISSUE TITLE
RFC: Idempotency

### ISSUE THREAD

**Issue by AndrewDryga** [Nebo15/sage#2]
```elixir
sage =
  new()
  |> with_idempotency(MyIdempotencyAdapter) // or with_persistency()
  |> run(:t1, ..)
  |> run(:t2, ..)
  |> checkpoint() # Ok, result is written to a persistent storage
  |> run(:t3, ..) # Fails only for the first time

execute(sage, [attr: "hello world"]) # Returns an error

execute(sage, [attr: "hello world"]) # Would continue from `:t2` by re-using persistent state which is stored as hash over all the arguments (or user-provided).
```

**Comment by erikreedstrom** [comment]
Interested in why this was closed. It reads like Stripe’s idempotency key, and seems like the logical extension of #9. 🤔
It fits our use case perfectly.

**Comment by AndrewDryga** [comment]
@erikreedstrom I've decided to have it out of scope because of involved complexity. Real idempotency is hard, even if we have persistence layer - then we should design it to store large amounts of data for longer durations (and make that storage duration configurable). Then storage should vary by an amount of data stored. Then we would have consistency issues because idempotency should be strongly consistent and using sagas would hurt availability.

So It's easy when you have just one node, but it's very hard to generalize and scale.

Sorry that response took so long :).
