### ISSUE TITLE
Allow the use of tuples in transaction names

### ISSUE THREAD

**Issue by elijahkim** [Nebo15/sage#29]
I believe Ecto.Multi allows this. It would be useful for cases in which you're doing the same operation multiple times. For example:

```
users = get_users()
Enum.reduce(users, Sage.new(), fn user, sage ->
  Sage.run(sage, {:promote_user, user.id}, &promote_user/2)
end)
```

or anything along those lines.

**Comment by AndrewDryga** [comment]
@elijahkim that's a nice idea 👍, I'll look into implementing it. Just no ETA for now :).

**Comment by elijahkim** [comment]
@AndrewDryga I can definitely take a first pass and put up a PR if you think it's useful

**Comment by AndrewDryga** [comment]
@elijahkim Sure, help is always appreciated. I think it should be pretty trivial to implement.
