### ISSUE TITLE
Readme not in sync with code

### ISSUE THREAD

**Issue by barttenbrinke** [Nebo15/sage#39]
Hi - first off let me say that sage is super cool! I've been using it in my project for a few weeks now and it REALLY clears things up.

One small thing that had me puzzled was that the readme examples all talk about fallbacks having /3 arguments: 
```
 |> run(:plans, &fetch_subscription_plans/2, &subscription_plans_circuit_breaker/3)
 |> run(:subscription, &create_subscription/2, &delete_subscription/3)
```
which gives you a compile error, as the code currently requires /4 :

```
effect_to_compensate, effects_so_far, name_and_reason, attrs
```

Would it be okay if I wrote a PR for this?

Thanks again! Bart

**Comment by AndrewDryga** [comment]
@barttenbrinke Hi, thank you for using Sage. And sure, feel free to send PR :).
