### ISSUE TITLE
Please add CHANGELOG

### ISSUE THREAD

**Issue by mtarnovan** [Nebo15/sage#51]
First, thank you for this lib, we use it in quite a few places ❤️ 

We recently tried upgrading from 0.4 to 0.6 and we see lots of test failures. Even if Sage is still pre 1.0, I think it would be good to keep a `CHANGELOG` and note breaking changes. As it is, we'll have to comb through a lot of commits to see what changed between 0.4 and 0.6, as those are quite some time apart.

Thanks,
Mihai

**Comment by timrogers** [comment]
Thanks for your great work on this library! We ❤️  it.

👍 on this. It's hard at the moment to know what changed as the new Git tag just mentions dependency bumps.

**Comment by AndrewDryga** [comment]
Hey guys.

I'll think how we can automate changelog building, indeed it's hard to track changes without any changelog or proper github releases. For now, you can check what was changed using git tags: https://github.com/Nebo15/sage/compare/0.4.0...0.6.0

**Comment by AndrewDryga** [comment]
I've started writing release notes and I'll try to keep doing that in future releases, thank you ❤️. Pre-1 changes are disruptive but I think we are close to 1.0 to stabilize the API.
