### ISSUE TITLE
Docs cannot lead to source

### ISSUE THREAD

**Issue by lud** [Nebo15/sage#64]
As `:source_ref` in `mix.exs` is set to `"v#\{@version\}"`, links to source in hexdocs lead to that kind of URLs: `https://github.com/Nebo15/sage/blob/v#{@version}/lib/sage.ex#L229`

Now that would be an easy pull request but I guess there is a reason for the escaping.

**Comment by AndrewDryga** [comment]
@lud this is just copy-pasted issue from somewhere, please go ahead and submit a PR ❤️.

**Comment by lud** [comment]
Please review: https://github.com/Nebo15/sage/pull/65
