### ISSUE TITLE
"inspect" implementation assumes atom stage names

### ISSUE THREAD

**Issue by peaceful-james** [Nebo15/sage#74]
I often use tuples for stage names, especially when performing sage transactions in a loop.

The `inspect` implementation raises an ArgumentError when stage name is a tuple.

Should be a simple fix. I'll open a PR next weekend if nobody else picks it up by then.

`lib/sage/inspect.ex:22`

```
  defp format_stage({name, operation}) do
    name = "#{Atom.to_string(name)}: "
    group(concat([name, nest(build_operation(operation), String.length(name))]))
  end
```

**Comment by AndrewDryga** [comment]
Great catch ❤️, closing in favor of PR! Thanks for it!
