### ISSUE TITLE
Broken Hexdocs link

### ISSUE THREAD

**Issue by Adzz** [Nebo15/sage#76]
Hey 👋 

When you click the view source button on Hexdocs:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/8428277/190453867-d4bc724c-ec82-4e5a-bd72-1c19ee4ef199.png">

It links to this URL which is broken `https://github.com/Nebo15/sage/blob/v#{@version}/lib/sage.ex#L1` 

I would fix but I don't know how 🙈 . Maybe updating hexdocs?

**Comment by AndrewDryga** [comment]
Hello @Adzz, thank you for reporting this. I've pushed a new version and the links should work now.
