### ISSUE TITLE
Would you be interested in giving this project away to someone who can shepherd it forward or a partner developer ?

### ISSUE THREAD

**Issue by midas** [Nebo15/sage#82]
First thanks so much for a such an awesome library!  It definitely makes things cleaner and easier to understand/test.

I notice no major work has been performed on it since 2022.  I have some needs for further features as I am actively using the project on three different production applications.  I also have some ideas for some short comings and/or annoyances I have encountered.

I am the creator of [productive](https://github.com/midas/productive), which is very similar to sage in many ways, although sage goes further.  Thus, I am familiar with the concepts and advantages and the inner workings of the library for this reason.

Let me know what you think at your earliest convenience.

Thanks!

Jason

**Comment by AndrewDryga** [comment]
Hello @midas,

The reason it doesn't get anything is because it's kinda "done". There are things we can improve but they will introduce breaking changes and almost nobody is asking for them.

Can you please tell a bit more what do you want to change?
